a = 4
b = 5
c = 6

print("a:", a, "b:", b, "c:", c)
print()
print("a + b + c =", a + b + c)
print("a + b - c =", a + b - c)
print("b - c - a =", b - c - a)
print()
print("c / a =", c / a)
print("c // a =", c // a)
print("c % a =", c % a)
print()
print("a ** 2=", a ** 2)
print("a ** 3=", a ** 3)
print("a ** 4=", a ** 4)
print()
print("a + b * c =", a + b * c)
print("(a + b) * c =", (a + b) * c)
print("a + b / c =", a + b / c)
print("a + b // c =", a + b // c)
print("a + b % c =", a + b % c)
print("(a + b) / c =", (a + b) / c)
print("(a + b) // c =", (a + b) // c)
print("(a + b) % c =", (a + b) % c)
